# NumPyの基本操作

In [6]:
import numpy as np

print('numpy のバージョンは：', np.__version__)

numpy のバージョンは： 1.17.0


## 配列の作成

In [7]:
a = np.array([1, 2, 3])
print('a=', a)

a= [1 2 3]


## 掛け算

In [8]:
a * 3

array([3, 6, 9])

## 足し算

In [9]:
a + 2

array([3, 4, 5])

## 配列の要素同士の四則演算 

In [10]:
b = np.array([1, 1, 4])
print('b=', b)

b= [1 1 4]


In [11]:
a + b

array([2, 3, 7])

In [12]:
a - b

array([ 0,  1, -1])

In [13]:
a / b

array([1.  , 2.  , 0.75])

In [14]:
a * b

array([ 1,  2, 12])

## ベクトルの内積

In [15]:
np.dot(a, b)

15

## 二次元ベクトルの内積

In [16]:
c = np.array([[1, 2], [3, 4]])
print('c=', c)
d = np.array([[3, 4], [1, 2]])
print('d=', d)

c= [[1 2]
 [3 4]]
d= [[3 4]
 [1 2]]


In [17]:
np.dot(c, d)

array([[ 5,  8],
       [13, 20]])

In [18]:
e = np.array([[1, 2, 3], [0.1, 0.2, 0.3], [7, 8, 9]])
print('e=', e)
f = np.array([[0.1, 0.2, 0.3], [1, 2, 3], [7, 8, 9]])
print('f=', f)

e= [[1.  2.  3. ]
 [0.1 0.2 0.3]
 [7.  8.  9. ]]
f= [[0.1 0.2 0.3]
 [1.  2.  3. ]
 [7.  8.  9. ]]


In [19]:
np.dot(f, e)

array([[  2.22,   2.64,   3.06],
       [ 22.2 ,  26.4 ,  30.6 ],
       [ 70.8 ,  87.6 , 104.4 ]])

## ndarrayの形状変換

In [20]:
g = np.arange(9).reshape((3, 3))
print('g=', g)

g= [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [21]:
g = g.reshape((9, 1))
print(g)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


## 要素がゼロの配列生成

In [22]:
zeros = np.zeros((3, 4))
print('zeros=', zeros)

zeros= [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


 ## 要素が1の配列を生成する

In [23]:
h = np.ones((3, 3))
print('h=', h)

h= [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## 未初期化の配列を生成する

In [24]:
p = np.empty((2, 3))
print('p=', p)

p= [[2.3727238e-316 0.0000000e+000 0.0000000e+000]
 [0.0000000e+000 0.0000000e+000 0.0000000e+000]]


## matrixで二次元配列の作成

In [25]:
k = np.matrix([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print('k=', k)

k= [[0 1 2]
 [3 4 5]
 [6 7 8]]


In [26]:
l = np.matrix([[1, 1, 1], [1, 1, 1], [1, 1, 1]])
print('l=', l)

m = np.dot(k, l)
print('m=', m)

l= [[1 1 1]
 [1 1 1]
 [1 1 1]]
m= [[ 3  3  3]
 [12 12 12]
 [21 21 21]]


## shapeで次元ごとの要素数を取得する

In [27]:
m.shape
print('m.shape', m.shape)

m.shape (3, 3)


## ndimで次元構造を取得する

In [28]:
m.ndim
print('m.ndim',m.ndim)

m.ndim 2


## 配列要素のデータ型dtype

In [29]:
m.dtype.name
print('m.dtype.name', m.dtype.name)

m.dtype.name int64


## １要素のバイト数itemsize

In [30]:
m.itemsize
print('m 配列内、各要素のbyte数：', m.itemsize)

m 配列内、各要素のbyte数： 8


## 配列の要素数size

In [31]:
m.size
print('m 総要素数：', m.size)

m 総要素数： 9


## arangeで配列を生成する

In [32]:
q = np.arange(1000000).reshape(1000, 1000)
print('q=', q)

q= [[     0      1      2 ...    997    998    999]
 [  1000   1001   1002 ...   1997   1998   1999]
 [  2000   2001   2002 ...   2997   2998   2999]
 ...
 [997000 997001 997002 ... 997997 997998 997999]
 [998000 998001 998002 ... 998997 998998 998999]
 [999000 999001 999002 ... 999997 999998 999999]]


In [33]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
x = np.arange(start=100, stop=600, step=100)
print(x)

[100 200 300 400 500]


## 配列要素データ型の変換astype

In [35]:
x_float = x.astype('float32')
print('x_float.dtype.name', x_float.dtype.name)
print(x_float) 

x_float.dtype.name float32
[100. 200. 300. 400. 500.]
